version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install unzip zip -y
      - export SDKMAN_DIR="/opt/sdkman"
      - curl -s "https://get.sdkman.io" | bash
      - . /opt/sdkman/bin/sdkman-init.sh
      - sdk install java
      - sdk install kotlin
      - sdk install gradle
  build:
    commands:
      - cd backend
      - gradle distTar
      - cd ..
  post_build:
    commands:
      - cp -r terraform/cicd/deploy/* backend/build/distributions

artifacts:
  files:
    - '**/*'
  base-directory: 'build/distributions'
