version: 0.2

phases:
  install:
    commands:
      - bash terraform/cicd/buildscripts/install.sh
  build:
    commands:
      - bash terraform/cicd/buildscripts/build.sh
  post_build:
    commands:
      - cp -r terraform/cicd/deploy/* backend/build/distributions

artifacts:
  files:
    - '**/*'
  base-directory: 'backend/build/distributions'
