#cloud-config
write_files:
  - path: /usr/bin/server_boot
    owner: root:root
    permissions: '0755'
    content: |
      #!/usr/bin/env bash

      apt-get update

      apt-get install unzip zip -y

      # install sdkman
      export SDKMAN_DIR="/opt/sdkman"
      curl -s "https://get.sdkman.io" | bash
      source /opt/sdkman/bin/sdkman-init.sh

      sdk install java

runcmd:
  - /usr/bin/server_boot
