#cloud-config
write_files:
  - path: /usr/bin/server_boot
    owner: root:root
    permissions: '0755'
    content: |
      #!/usr/bin/env bash

      apt-get update

      apt-get install unzip zip -y

      # install sdkman
      curl -s "https://get.sdkman.io" | bash
      source ~/.sdkman/bin/sdkman-init.sh

      sdk install java
      sdk install gradle
      sdk install kotlin
      # install git
      apt-get install git

      cd /opt
      git clone https://github.com/mikkeldamsgaard/scoutcamp.git

      cd scoutcamp/backend
      gradle build
      nohup gradle run > /var/log/scoutcamp.log &

runcmd:
  - /usr/bin/server_boot
